### ISSUE TITLE
having a bit of issue adding my firmware images to this.

### ISSUE THREAD

**Issue by hanetzer** [orangecms/utk-web#21]
Was hoping you could just add them to the currently online version. You can get a copy
of my firmware from here: https://www.asus.com/us/Motherboards/ROG-CROSSHAIR-VII-HERO-WI-FI/HelpDesk_Warranty/

**Comment by orangecms** [comment]
done; it's lingering in a branch here now, which is a bit of a mess to clean up... enjoy the live version online :)
